import { Question } from './types'

export const questions: Question[] = [
  {
    id: 'url-shortener',
    title: 'Design a URL Shortener',
    company: 'Meta',
    difficulty: 'medium',
    description: 'Design a service like bit.ly that takes a long URL and returns a short alias. The short URL should redirect to the original URL when visited.',
    requirements: {
      functional: [
        'Generate a unique short URL for a given long URL',
        'Redirect short URL to the original long URL',
        'Support custom aliases',
        'Track click analytics (count, timestamp, location)',
        'URLs expire after a configurable TTL',
      ],
      nonFunctional: [
        '100M URLs created per day (~1200/sec writes)',
        '10B redirects per day (~115K/sec reads)',
        'Read:write ratio 100:1',
        'Redirection latency < 10ms (p99)',
        '99.99% availability',
        'Short URLs are 7 characters (base62)',
      ],
    },
    rubric: {
      required: [
        'Load Balancer',
        'App Server',
        'SQL DB or NoSQL DB',
        'Cache (Redis)',
        'DNS',
      ],
      recommended: [
        'CDN',
        'Message Queue',
        'Worker',
        'Object Store',
      ],
      connections: [
        { from: 'Client', to: 'DNS' },
        { from: 'DNS', to: 'Load Balancer' },
        { from: 'Load Balancer', to: 'App Server' },
        { from: 'App Server', to: 'Cache' },
        { from: 'App Server', to: 'SQL DB' },
        { from: 'App Server', to: 'NoSQL DB' },
      ],
    },
  },
  {
    id: 'rate-limiter',
    title: 'Design a Rate Limiter',
    company: 'Google',
    difficulty: 'medium',
    description: 'Design a distributed rate limiter that limits the number of requests a client can make to an API within a time window, preventing abuse and ensuring fair usage.',
    requirements: {
      functional: [
        'Limit requests per user/IP per time window',
        'Support multiple algorithms: token bucket, sliding window, fixed window',
        'Return 429 Too Many Requests when limit exceeded',
        'Different rate limits for different API endpoints',
        'Real-time limit status in response headers',
      ],
      nonFunctional: [
        'Decision latency < 1ms (added overhead)',
        '1M requests per second throughput',
        'Accurate across distributed nodes',
        'No single point of failure',
        '99.999% availability',
      ],
    },
    rubric: {
      required: [
        'Load Balancer',
        'App Server',
        'Redis Cache',
        'API Gateway',
      ],
      recommended: [
        'Message Queue',
        'Worker',
        'SQL DB',
        'Firewall',
      ],
      connections: [
        { from: 'Client', to: 'API Gateway' },
        { from: 'API Gateway', to: 'Load Balancer' },
        { from: 'Load Balancer', to: 'App Server' },
        { from: 'App Server', to: 'Redis Cache' },
        { from: 'API Gateway', to: 'Redis Cache' },
      ],
    },
  },
  {
    id: 'news-feed',
    title: 'Design a News Feed',
    company: 'Meta',
    difficulty: 'hard',
    description: 'Design a personalized news feed system like Facebook or Twitter. Users can post content, follow others, and see a ranked feed of posts from people they follow.',
    requirements: {
      functional: [
        'Users can create posts (text, images, videos)',
        'Users can follow/unfollow other users',
        'Feed shows ranked posts from followed users',
        'Support likes, comments, and shares',
        'Real-time updates when new posts arrive',
        'Infinite scroll pagination',
      ],
      nonFunctional: [
        '500M daily active users',
        'Each user sees feed of up to 500 posts',
        'Feed generation < 200ms (p99)',
        'Write fanout for users with <10K followers (push model)',
        'Pull model for celebrity accounts (>10K followers)',
        '99.9% availability',
        'Posts are eventually consistent (2-3 seconds lag acceptable)',
      ],
    },
    rubric: {
      required: [
        'Load Balancer',
        'App Server',
        'SQL DB',
        'NoSQL DB',
        'Cache (Redis)',
        'Message Queue',
        'CDN',
      ],
      recommended: [
        'Worker',
        'Object Store',
        'Search Engine',
        'Event Bus',
        'API Gateway',
      ],
      connections: [
        { from: 'Client', to: 'CDN' },
        { from: 'Client', to: 'Load Balancer' },
        { from: 'Load Balancer', to: 'App Server' },
        { from: 'App Server', to: 'Cache' },
        { from: 'App Server', to: 'SQL DB' },
        { from: 'App Server', to: 'NoSQL DB' },
        { from: 'App Server', to: 'Message Queue' },
        { from: 'Message Queue', to: 'Worker' },
        { from: 'Worker', to: 'Cache' },
        { from: 'Worker', to: 'Object Store' },
      ],
    },
  },
  {
    id: 'pastebin',
    title: 'Design Pastebin',
    company: 'Amazon',
    difficulty: 'easy',
    description: 'Design a Pastebin system that allows users to store and share text snippets, which is challenging due to the high volume of user requests and the need for low latency and high availability.',
    requirements: {
      functional: [
        'Users can create and edit text snippets',
        'Users can share text snippets via a unique URL',
        'System supports syntax highlighting for various programming languages',
        'System allows users to search for text snippets by keyword',
        'System supports user authentication and authorization',
      ],
      nonFunctional: [
        'Handle 10,000 concurrent users with an average response time of 200ms',
        'Achieve 99.99% availability with less than 5 minutes of downtime per month',
        'Support 100,000 new text snippets per day with an average size of 1KB',
        'Ensure data consistency across all components with a latency of less than 1 second',
        'Comply with GDPR and CCPA regulations for user data protection',
      ],
    },
    rubric: {
      required: ["Client", "API Gateway", "App Server", "SQL DB", "Redis Cache"],
      recommended: ["CDN", "Load Balancer", "Object Store"],
      connections: [
        { from: 'Client', to: 'API Gateway' },
        { from: 'API Gateway', to: 'App Server' },
        { from: 'App Server', to: 'SQL DB' },
        { from: 'App Server', to: 'Redis Cache' },
        { from: 'API Gateway', to: 'CDN' },
      ],
    },
  },
  {
    id: 'instagram',
    title: 'Design Instagram',
    company: 'Facebook',
    difficulty: 'easy',
    description: 'Design Instagram, a social media platform that allows users to share photos and videos, with a focus on scalability and performance to handle millions of users.',
    requirements: {
      functional: [
        'User authentication and authorization',
        'Image and video upload and processing',
        'Feed generation and post display',
        'Commenting and liking functionality',
        'Search and hashtag functionality',
      ],
      nonFunctional: [
        'Handle 1 million new users per day',
        'Achieve an average latency of 200ms for feed generation',
        'Maintain 99.99% availability with less than 5 minutes of downtime per month',
        'Support 100,000 concurrent users',
        'Process 10,000 new posts per minute',
      ],
    },
    rubric: {
      required: ["App Server", "SQL DB", "Load Balancer", "Object Store", "CDN"],
      recommended: ["Redis Cache", "Message Queue", "Worker"],
      connections: [
        { from: 'Client', to: 'CDN' },
        { from: 'Client', to: 'Load Balancer' },
        { from: 'Load Balancer', to: 'App Server' },
        { from: 'App Server', to: 'SQL DB' },
        { from: 'App Server', to: 'Object Store' },
        { from: 'App Server', to: 'Redis Cache' },
      ],
    },
  },
  {
    id: 'dropbox-or-google-drive',
    title: 'Design Dropbox or Google Drive',
    company: 'Dropbox',
    difficulty: 'medium',
    description: 'Design a cloud-based file storage system like Dropbox or Google Drive that allows users to store and access files from anywhere, challenging due to large data volumes, sync conflicts, and security requirements.',
    requirements: {
      functional: [
        'User authentication and authorization',
        'File upload and download',
        'File sharing and collaboration',
        'File versioning and history',
        'Search and retrieval of files',
      ],
      nonFunctional: [
        'Handle 10 million concurrent users',
        'Ensure 99.99% availability with less than 1 minute of downtime per month',
        'Achieve average latency of less than 200ms for file uploads and downloads',
        'Store at least 100 petabytes of data',
        'Support 100,000 file uploads per second',
      ],
    },
    rubric: {
      required: ["API Gateway", "App Server", "Object Store", "SQL DB"],
      recommended: ["Load Balancer", "Redis Cache", "Message Queue", "Worker"],
      connections: [
        { from: 'Client', to: 'API Gateway' },
        { from: 'API Gateway', to: 'App Server' },
        { from: 'App Server', to: 'Object Store' },
        { from: 'App Server', to: 'SQL DB' },
        { from: 'App Server', to: 'Redis Cache' },
      ],
    },
  },
  {
    id: 'facebook-messenger-or-whatsapp',
    title: 'Design Facebook Messenger or WhatsApp',
    company: 'Facebook',
    difficulty: 'medium',
    description: 'Design a messaging system like Facebook Messenger or WhatsApp that handles a large volume of messages with low latency and high availability, challenging due to real-time delivery and end-to-end encryption at scale.',
    requirements: {
      functional: [
        'Support one-on-one and group messaging',
        'Enable file sharing and media transfer',
        'Implement end-to-end encryption for secure communication',
        'Provide real-time notification and update mechanisms',
        'Allow users to manage their contacts and message history',
      ],
      nonFunctional: [
        'Handle 100 million concurrent users with 1 million messages per second',
        'Ensure average latency of less than 100ms for message delivery',
        'Achieve 99.99% availability with less than 1 hour of downtime per year',
        'Support 1000 new user registrations per minute',
        'Process 5000 search queries per second with a response time of less than 50ms',
      ],
    },
    rubric: {
      required: ["Load Balancer", "App Server", "NoSQL DB", "Message Queue"],
      recommended: ["Redis Cache", "Object Store", "CDN"],
      connections: [
        { from: 'Client', to: 'Load Balancer' },
        { from: 'Load Balancer', to: 'App Server' },
        { from: 'App Server', to: 'NoSQL DB' },
        { from: 'App Server', to: 'Redis Cache' },
        { from: 'App Server', to: 'Message Queue' },
      ],
    },
  },
  {
    id: 'twitter-for-millions-of-users',
    title: 'Design Twitter for millions of users',
    company: 'Uber',
    difficulty: 'medium',
    description: 'Design a Twitter-like system that can handle millions of users posting, following, and searching in real-time, with the main challenge being feed fanout at scale for both celebrities and regular users.',
    requirements: {
      functional: [
        'Handle user registration and login functionality',
        'Allow users to create, edit, and delete tweets',
        'Implement a search function to find tweets based on keywords',
        'Enable users to follow other users and view their tweets in a feed',
        'Support direct messaging between users',
      ],
      nonFunctional: [
        'Handle 10,000 concurrent users with an average latency of 200ms',
        'Ensure 99.99% availability with less than 5 minutes of downtime per month',
        'Process 100,000 tweets per second with a maximum latency of 1 second',
        'Support 1 million new user registrations per day',
        'Achieve an average search query latency of 50ms',
      ],
    },
    rubric: {
      required: ["Load Balancer", "App Server", "SQL DB", "NoSQL DB", "Cache (Redis)"],
      recommended: ["Message Queue", "Worker", "Search Engine", "CDN"],
      connections: [
        { from: 'Client', to: 'Load Balancer' },
        { from: 'Load Balancer', to: 'App Server' },
        { from: 'App Server', to: 'SQL DB' },
        { from: 'App Server', to: 'NoSQL DB' },
        { from: 'App Server', to: 'Redis Cache' },
        { from: 'App Server', to: 'Message Queue' },
        { from: 'Message Queue', to: 'Worker' },
      ],
    },
  },
  {
    id: 'youtube-or-netflix',
    title: 'Design Youtube or Netflix',
    company: 'Facebook',
    difficulty: 'medium',
    description: 'Design a scalable video streaming service like YouTube or Netflix to handle millions of concurrent viewers with low buffering, challenging due to CDN architecture, adaptive bitrate streaming, and massive storage needs.',
    requirements: {
      functional: [
        'User authentication and authorization',
        'Video content upload and processing',
        'Search and recommendation functionality',
        'Real-time analytics and reporting',
        'Multi-device support for streaming',
      ],
      nonFunctional: [
        'Support 10 million concurrent users with less than 1-second latency',
        'Achieve 99.99% availability with less than 1 hour of downtime per year',
        'Handle 100,000 new user sign-ups per hour',
        'Process 1 million video uploads per day',
        'Ensure an average video load time of less than 500ms',
      ],
    },
    rubric: {
      required: ["Load Balancer", "App Server", "Object Store", "CDN"],
      recommended: ["Redis Cache", "Message Queue", "Worker", "SQL DB"],
      connections: [
        { from: 'Client', to: 'CDN' },
        { from: 'Client', to: 'Load Balancer' },
        { from: 'Load Balancer', to: 'App Server' },
        { from: 'App Server', to: 'Object Store' },
        { from: 'App Server', to: 'SQL DB' },
        { from: 'App Server', to: 'Redis Cache' },
        { from: 'App Server', to: 'Message Queue' },
        { from: 'Message Queue', to: 'Worker' },
      ],
    },
  },
  {
    id: 'distributed-metrics-logging-and-aggregation-system',
    title: 'Design a Distributed Metrics Logging and Aggregation System',
    company: 'Google',
    difficulty: 'hard',
    description: 'Design a distributed system to collect, store, and aggregate metrics from thousands of services in real-time, challenging due to high ingestion rates, time-series storage, and query performance at petabyte scale.',
    requirements: {
      functional: [
        'Collect metrics data from multiple sources such as App Server and Mobile App',
        'Store and process large volumes of metrics data in real-time',
        'Provide querying and filtering capabilities for metrics data',
        'Support multiple data formats such as JSON and CSV',
        'Handle errors and exceptions in metrics data collection and processing',
      ],
      nonFunctional: [
        'Handle 100,000 requests per second with average latency of 50ms',
        'Achieve 99.99% availability with less than 5 minutes of downtime per year',
        'Store at least 1 year of metrics data with total storage capacity of 100TB',
        'Support 10,000 concurrent users querying metrics data',
        'Process 1 million metrics data points per second with less than 1% data loss',
      ],
    },
    rubric: {
      required: ["API Gateway", "NoSQL DB", "Message Queue", "Worker"],
      recommended: ["Redis Cache", "Data Warehouse", "Load Balancer"],
      connections: [
        { from: 'Client', to: 'API Gateway' },
        { from: 'API Gateway', to: 'Message Queue' },
        { from: 'Message Queue', to: 'Worker' },
        { from: 'Worker', to: 'NoSQL DB' },
        { from: 'Worker', to: 'Data Warehouse' },
        { from: 'API Gateway', to: 'Redis Cache' },
      ],
    },
  },
  {
    id: 'distributed-stream-processing-system-like-kafka',
    title: 'Design a Distributed Stream Processing System like Kafka',
    company: 'Amazon',
    difficulty: 'hard',
    description: 'Design a distributed stream processing system like Kafka to handle high-volume and high-velocity data streams, challenging due to the need for fault tolerance, exactly-once delivery guarantees, and horizontal scalability.',
    requirements: {
      functional: [
        'Handle 10,000 messages per second from multiple sources',
        'Support multiple data formats such as JSON, Avro, and Protobuf',
        'Provide exactly-once processing guarantees for messages',
        'Allow for real-time data aggregation and filtering',
        'Support integration with multiple downstream systems for data consumption',
      ],
      nonFunctional: [
        'Achieve end-to-end latency of less than 100ms for 99.9% of messages',
        'Ensure system availability of at least 99.99% with less than 5 minutes of downtime per year',
        'Handle peak throughput of 100,000 messages per second with less than 1% message loss',
        'Support 10,000 concurrent connections from producers and consumers',
        'Guarantee data durability with less than 1% data loss in the event of a failure',
      ],
    },
    rubric: {
      required: ["Message Queue", "Load Balancer", "App Server", "NoSQL DB"],
      recommended: ["Redis Cache", "Worker", "Data Warehouse"],
      connections: [
        { from: 'Client', to: 'Load Balancer' },
        { from: 'Load Balancer', to: 'App Server' },
        { from: 'App Server', to: 'Message Queue' },
        { from: 'Message Queue', to: 'Worker' },
        { from: 'Worker', to: 'NoSQL DB' },
        { from: 'Worker', to: 'Data Warehouse' },
      ],
    },
  },
  {
    id: 'typeahead-suggestionautocomplete',
    title: 'Design Typeahead Suggestion/Autocomplete',
    company: 'Facebook',
    difficulty: 'hard',
    description: 'Design a typeahead suggestion/autocomplete system that provides relevant search results as users type, which is challenging due to the need for low-latency responses and handling a large volume of concurrent requests. The system should be able to handle millions of users and provide accurate suggestions within milliseconds.',
    requirements: {
      functional: [
        'Handle user input and provide relevant search suggestions',
        'Support multiple data sources for suggestions, such as user profiles and product catalogs',
        'Implement a ranking algorithm to prioritize suggestions based on relevance and user behavior',
        'Handle errors and exceptions, such as network failures and data source unavailability',
        'Support multiple languages and character sets',
      ],
      nonFunctional: [
        'Handle 10,000 concurrent requests per second with an average latency of 50ms',
        'Achieve an availability SLA of 99.99% and a uptime of 23:59:59 per day',
        'Support 100 million registered users with an average of 10 searches per user per day',
        'Store and index 1 billion searchable records with an average size of 1KB per record',
        'Handle a peak traffic of 50,000 requests per second during holiday seasons',
      ],
    },
    rubric: {
      required: ["API Gateway","App Server","Redis Cache"],
      recommended: ["Load Balancer","CDN Cache"],
      connections: [
        { from: 'Client', to: 'API Gateway' },
        { from: 'API Gateway', to: 'App Server' },
        { from: 'App Server', to: 'Redis Cache' },
        { from: 'App Server', to: 'SQL DB' },
        { from: 'API Gateway', to: 'Load Balancer' },
      ],
    },
  },
]

export function getQuestion(id: string): Question | undefined {
  return questions.find((q) => q.id === id)
}
